# Generated by Django 3.2.16 on 2022-11-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221116_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='postuladorpaseo',
            name='cv',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
